env:
  name: 'puoribor'
  board_size: 9
  max_walls: 10 

stm:
  filters: 192
  block_num: 5
  value_dim: 256
  input_channel: 25
  output_channel: 4
  
  saving_point: 'checkpoints/pretrained/'
  inference: 0
  training: 1

mcts:
  temp: 1.414
  sim_num: 1000


hardware:
  num_cpus: 8


pretraining:
  lr: 1e-6
  epochs: 100
  batch_size: 2048