env:
  name: 'puoribor'
  board_size: 9
  action_space: (4, 9, 9)
  max_walls: 10

stm:
  block_num: 5
  block_dims: [(25,32,64),(64,128,192),(192,192,192),(192,192,192),(192,192,4)]
  saving_point: 'checkpoints/puoribor/'


mcts:
  temp: 1.414
  sim_num: 1000


