env:
  name: 'puoribor'
  board_size: 9
  max_walls: 10 

stm:
  temp: 1.0
  filters: 256
  block_num: 20
  value_dim: 256
  input_channel: 25
  output_channel: 4

mcts:
  temp: 1.414
  sim_num: 1000


hardware:
  num_cpus: 8


pretrain:
  lr: 1e-6
  epochs: 50
  batch_size: 512
  saving_point: '../../checkpoints/pretrained/'